export enum ZenkyInjection {
  ProductsSource = 'zenky:products:source',
  Category = 'zenky:category',
  CategoryNotFound = 'zenky:category:notFound',
  Collection = 'zenky:collection',
  CollectionNotFound = 'zenky:collection:notFound',
  Offer = 'zenky:offer',
  OfferNotFound = 'zenky:offer:notFound',
  CategoryContext = 'zenky:context:category',
  CategoryContextNotFound = 'zenky:context:category:notFound',
  GroupContext = 'zenky:context:category',
  GroupContextNotFound = 'zenky:context:category:notFound',
  VariantOptionContext = 'zenky:context:variant_option',
  VariantOptionContextNotFound = 'zenky:context:variant_option:notFound',
  VariantOptionValueContext = 'zenky:context:variant_option_value',
  VariantOptionValueContextNotFound = 'zenky:context:variant_option_value:notFound',
}
